### PR TITLE
LLVM 8

### LINKED ISSUE #65: LLVM 8 binding generation fails on macOS
This happens on the Azure build server which currently runs on Mac OS X 10.13 and on Mojave 10.14 when LLVM 8 is installed via `brew install llvm`.

`rust-skia/skia-bindings/skia/include/private/../private/SkOnce.h:11:10: fatal error: 'atomic' file not found`

Not sure why, the Skia build is successful.

### PR DESCRIPTION
**Pull request by pragmatrix**
The Azure Linux and macOS images seem to have LLVM 8 preinstalled and recent builds went fine. So I think we can remove the additional installation steps and recommend LLVM 8 in the readme ([rendered](https://github.com/rust-skia/rust-skia/blob/llvm-8/README.md)).

**Update**: No, Ubuntu builds with 6.0.1 and macOS with Apple LLVM 10. I was confused because of the version output of rustc which prints the LLVM version itself was built with, so I've added the output of `clang --version` as a pipelines step to this PR.

Closes #65

### CODE REVIEW

**Comment by pragmatrix** [comment]
Perhaps we should just keep the default 6.0.1 for ubuntu 16, Apple LLVM 10 on macOS and install 8.0.0 (the recommended one) for Windows?

For a final decision, I think it's best to block this PR until #116  is resolved to get some feedback about the layout consistency of the generated bindings on different platforms with different LLVM versions.

**Comment by pragmatrix** [comment]
Interestingly, the "brew install llvm" on the macOS image had no effect because the paths were not set, instead, Apple LLVM 10 was used. I've removed that line.

**Comment by pragmatrix** [comment]
Even though we have no data yet on how the different LLVM versions affect the layout of the bindings, I will unblock this because the result should be "better than before". 

Ready for a review.
