### ISSUE TITLE
Issue with MacOS 14.7 binding compiling 

### ISSUE THREAD

**Issue by danbishop-canva** [rust-skia/rust-skia#1032]
After updating from MacOS 14.6.1 to 14.7, there now seems to be an issue with bindings during compiling. This is for skia 0.66.1, so maybe newer versions don't have this problem but I doubt it because it has only just appeared with this new mac version. 

The errors I was receiving are:

```
error[E0412]: cannot find type `_Pred` in this scope
   --> /bindings.rs:191:29
    |
191 |     pub _base: std___1__And<_Pred>,
    |                             ^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
190 | pub struct std___1_tuple__EnableUTypesCtor<_Pred> {
    |                                           +++++++

error[E0412]: cannot find type `SkLRUCache` in this scope
     --> /bindings.rs:30923:23
      |
30923 |     pub fLRUCacheMap: SkLRUCache<
      |                       ^^^^^^^^^^ not found in this scope
```

I noticed that system llvm/clang had been updated during the update from 15.0.0 to 16.0.0. So I manually installed llvm 15.0.0 and set the PATH, CPPFLAGS, and LDFLAGS to this llvm version. This provided a different error which seems more useful.

```
  FAILED: obj/src/utils/mac/libskia.SkCTFont.o 
  clang++ -MD -MF obj/src/utils/mac/libskia.SkCTFont.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ENABLE_PRECOMPILE -DSK_ASSUME_GL=1 -DSK_USE_PERFETTO -DSK_GAMMA_EXPONENT=1.2 -DSK_GAMMA_CONTRAST=0.2 -DSK_ENABLE_API_AVAILABLE -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DSK_TYPEFACE_FACTORY_FREETYPE -DSK_SUPPORT_PDF -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_HAS_WUFFS_LIBRARY -DSK_XML -I../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia -Wno-attributes -ffp-contract=off -fstrict-aliasing -fPIC -fvisibility=hidden -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -target arm64-apple-macos11 -O3 -I/Users/danbishop/work/canva/target/cargo/debug/build/mozjpeg-sys-b7f91fdff3b38a80/out/include -I/Users/danbishop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozjpeg-sys-2.0.5/vendor -O0 -std=c++17 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCTFont.cpp -o obj/src/utils/mac/libskia.SkCTFont.o
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCTFont.cpp:17:
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCTFont.h:15:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:21:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:20:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTLine.h:140:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'CFMutableStringRef'?
      CFAttributedStringRef attrString ) CT_AVAILABLE(macos(10.5), ios(3.2), watchos(2.0), tvos(9.0));
      ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:511:70: note: 'CFMutableStringRef' declared here
  typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableString) __CFString * CFMutableStringRef;
                                                                       ^
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCTFont.cpp:17:
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCTFont.h:15:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:21:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:104:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'CFMutableStringRef'?
      CFAttributedStringRef string ) CT_AVAILABLE(macos(10.5), ios(3.2), watchos(2.0), tvos(9.0));
      ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:511:70: note: 'CFMutableStringRef' declared here
  typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableString) __CFString * CFMutableStringRef;
                                                                       ^
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCTFont.cpp:17:
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCTFont.h:15:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:21:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:132:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'CFMutableStringRef'?
      CFAttributedStringRef string,
      ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:511:70: note: 'CFMutableStringRef' declared here
  typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableString) __CFString * CFMutableStringRef;
                                                                       ^
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCTFont.cpp:17:
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCTFont.h:15:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:85:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'CFMutableStringRef'?
      CFAttributedStringRef attrString ) CT_AVAILABLE(macos(10.5), ios(3.2), watchos(2.0), tvos(9.0));
      ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:511:70: note: 'CFMutableStringRef' declared here
  typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableString) __CFString * CFMutableStringRef;
                                                                       ^
  4 errors generated.
  [536/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/SkShadowTessellator.cpp
  [537/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/SkLayerDrawLooper.cpp
  [538/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/SkBlenders.cpp
  [539/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/Sk1DPathEffect.cpp
  [540/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/Sk2DPathEffect.cpp
  [541/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/SkShadowUtils.cpp
  [542/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/SkEmbossMask.cpp
  [543/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/SkHighContrastFilter.cpp
  [544/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCreateCGImageRef.cpp
  FAILED: obj/src/utils/mac/libskia.SkCreateCGImageRef.o 
  clang++ -MD -MF obj/src/utils/mac/libskia.SkCreateCGImageRef.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ENABLE_PRECOMPILE -DSK_ASSUME_GL=1 -DSK_USE_PERFETTO -DSK_GAMMA_EXPONENT=1.2 -DSK_GAMMA_CONTRAST=0.2 -DSK_ENABLE_API_AVAILABLE -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DSK_TYPEFACE_FACTORY_FREETYPE -DSK_SUPPORT_PDF -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_HAS_WUFFS_LIBRARY -DSK_XML -I../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia -Wno-attributes -ffp-contract=off -fstrict-aliasing -fPIC -fvisibility=hidden -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -target arm64-apple-macos11 -O3 -I/Users/danbishop/work/canva/target/cargo/debug/build/mozjpeg-sys-b7f91fdff3b38a80/out/include -I/Users/danbishop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mozjpeg-sys-2.0.5/vendor -O0 -std=c++17 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCreateCGImageRef.cpp -o obj/src/utils/mac/libskia.SkCreateCGImageRef.o
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCreateCGImageRef.cpp:15:
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/include/utils/mac/SkCGUtils.h:19:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:21:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:20:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTLine.h:140:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'CFMutableStringRef'?
      CFAttributedStringRef attrString ) CT_AVAILABLE(macos(10.5), ios(3.2), watchos(2.0), tvos(9.0));
      ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:511:70: note: 'CFMutableStringRef' declared here
  typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableString) __CFString * CFMutableStringRef;
                                                                       ^
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCreateCGImageRef.cpp:15:
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/include/utils/mac/SkCGUtils.h:19:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:21:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:104:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'CFMutableStringRef'?
      CFAttributedStringRef string ) CT_AVAILABLE(macos(10.5), ios(3.2), watchos(2.0), tvos(9.0));
      ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:511:70: note: 'CFMutableStringRef' declared here
  typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableString) __CFString * CFMutableStringRef;
                                                                       ^
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCreateCGImageRef.cpp:15:
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/include/utils/mac/SkCGUtils.h:19:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:21:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:132:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'CFMutableStringRef'?
      CFAttributedStringRef string,
      ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:511:70: note: 'CFMutableStringRef' declared here
  typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableString) __CFString * CFMutableStringRef;
                                                                       ^
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/utils/mac/SkCreateCGImageRef.cpp:15:
  In file included from ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/include/utils/mac/SkCGUtils.h:19:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:85:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'CFMutableStringRef'?
      CFAttributedStringRef attrString ) CT_AVAILABLE(macos(10.5), ios(3.2), watchos(2.0), tvos(9.0));
      ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:511:70: note: 'CFMutableStringRef' declared here
  typedef struct CF_BRIDGED_MUTABLE_TYPE(NSMutableString) __CFString * CFMutableStringRef;
                                                                       ^
  4 errors generated.
  [545/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/SkCornerPathEffect.cpp
  [546/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/SkEmbossMaskFilter.cpp
  [547/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/SkDiscretePathEffect.cpp
  [548/1219] compile ../../../../../../../../../.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/skia/src/effects/SkDashPathEffect.cpp
  ninja: build stopped: subcommand failed.

  --- stderr
  thread 'main' panicked at /Users/danbishop/.cargo/git/checkouts/rust-skia-a61302b13b557138/77f9510/skia-bindings/build_support/skia/config.rs:342:5:
  `ninja` returned an error, please check the output for details.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It looks like some system headers have been updated in this new mac os update. Does anyone have any ideas on how to solve this?

**Comment by pragmatrix** [comment]
Thank you for the report. These errors do not appear in master. I've updated macOS to 14.7 and had no problem building it with all features on macOS using Apple LLVM 16. Presumably #977 is one of the MRs you might need to patch in if you want to stay on 0.66, but I strongly suggest to update if possible.
