### ISSUE TITLE
Can't build on OS X 10.15.3 Catalina 

### ISSUE THREAD

**Issue by romanzes** [rust-skia/rust-skia#304]
Hi all, when I try to build rust-skia on Mac OS it gives me the following output in stderr:
```
--- stderr
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-apple-darwin
Thread model: posix
InstalledDir: 
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
ignoring duplicate directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /Users/romanpetrenko/workspace/rust-skia/skia-bindings/skia
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks
 /usr/local/opt/llvm@7/include/c++/v1
 /usr/local/opt/llvm@7/lib/clang/7.0.1/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:65:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u16'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:199:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u32'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:215:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u32'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:362:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u64'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:378:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u64'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/lzcntintrin.h:62:10: error: use of undeclared identifier '__builtin_ia32_lzcnt_u32'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/lzcntintrin.h:79:10: error: use of undeclared identifier '__builtin_ia32_lzcnt_u32'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/lzcntintrin.h:112:10: error: use of undeclared identifier '__builtin_ia32_lzcnt_u64'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512fintrin.h:8441:24: error: use of undeclared identifier '__builtin_ia32_kmovw'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512fintrin.h:8446:21: error: use of undeclared identifier '__builtin_ia32_kmovw'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512fintrin.h:8451:21: error: use of undeclared identifier '__builtin_ia32_kmovw'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512fintrin.h:8456:23: error: use of undeclared identifier '__builtin_ia32_kmovw'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:41:10: error: use of undeclared identifier '__builtin_ia32_knotsi'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:47:10: error: use of undeclared identifier '__builtin_ia32_knotdi'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:53:21: error: use of undeclared identifier '__builtin_ia32_kandsi'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:59:21: error: use of undeclared identifier '__builtin_ia32_kanddi'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:65:21: error: use of undeclared identifier '__builtin_ia32_kandnsi'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:71:21: error: use of undeclared identifier '__builtin_ia32_kandndi'
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:77:21: error: use of undeclared identifier '__builtin_ia32_korsi'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:65:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u16', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:199:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u32', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:215:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u32', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:362:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u64', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/bmiintrin.h:378:10: error: use of undeclared identifier '__builtin_ia32_tzcnt_u64', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/lzcntintrin.h:62:10: error: use of undeclared identifier '__builtin_ia32_lzcnt_u32', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/lzcntintrin.h:79:10: error: use of undeclared identifier '__builtin_ia32_lzcnt_u32', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/lzcntintrin.h:112:10: error: use of undeclared identifier '__builtin_ia32_lzcnt_u64', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512fintrin.h:8441:24: error: use of undeclared identifier '__builtin_ia32_kmovw', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512fintrin.h:8446:21: error: use of undeclared identifier '__builtin_ia32_kmovw', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512fintrin.h:8451:21: error: use of undeclared identifier '__builtin_ia32_kmovw', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512fintrin.h:8456:23: error: use of undeclared identifier '__builtin_ia32_kmovw', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:41:10: error: use of undeclared identifier '__builtin_ia32_knotsi', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:47:10: error: use of undeclared identifier '__builtin_ia32_knotdi', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:53:21: error: use of undeclared identifier '__builtin_ia32_kandsi', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:59:21: error: use of undeclared identifier '__builtin_ia32_kanddi', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:65:21: error: use of undeclared identifier '__builtin_ia32_kandnsi', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:71:21: error: use of undeclared identifier '__builtin_ia32_kandndi', err: true
/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include/avx512bwintrin.h:77:21: error: use of undeclared identifier '__builtin_ia32_korsi', err: true
```

One of the lines that attracted my attention was this:
```
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
```
It's true that I don't have this directory, however, `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks` is present on my machine (note the `System` part).

**Comment by pragmatrix** [comment]
@romanzes I think that this is a similar problem as reported in #228. You may need to uninstall llvm7 or tweak the environment values: `PATH`, `CPPFLAGS`, and `LDFLAGS`. If homebrew is used, the values are displayed after the installation.

**Comment by romanzes** [comment]
@pragmatrix thank you, uninstalling brew's LLVM helped 👍
